ERROR - 2022-12-01 02:51:08 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'vedatrix', 3306, '', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#3 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2022-12-01 02:51:08 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `contact` (`name`, `email`, `phone`, `message`) VALUES (:name:, :email:, :phone:, :message:)', [...], false)
 3 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 6 APPPATH\Controllers\Myhome.php(32): CodeIgniter\Model->insert([...], false)
 7 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
 8 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
 9 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-01 02:51:45 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:45:25 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:47:32 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:49:48 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:53:05 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:53:06 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:53:06 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:53:07 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:53:07 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 03:54:27 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:08:27 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:29:16 --> mysqli_sql_exception: Duplicate entry 'jakljlka@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:29:55 --> mysqli_sql_exception: Duplicate entry 'jakljlka@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:41:19 --> mysqli_sql_exception: Duplicate entry 'dlfjdl@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:41:20 --> mysqli_sql_exception: Duplicate entry 'dlfjdl@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:41:20 --> mysqli_sql_exception: Duplicate entry 'dlfjdl@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:41:20 --> mysqli_sql_exception: Duplicate entry 'dlfjdl@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:41:21 --> mysqli_sql_exception: Duplicate entry 'dlfjdl@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 04:58:39 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 05:00:29 --> mysqli_sql_exception: Column 'email' cannot be null in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 05:37:26 --> mysqli_sql_exception: Duplicate entry 'vijaykumar@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 05:37:29 --> mysqli_sql_exception: Duplicate entry 'vijaykumar@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-01 05:52:23 --> Unsupported operand types: string + string
in APPPATH\Controllers\Myhome.php on line 39.
 1 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
 2 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-01 05:52:32 --> mysqli_sql_exception: Duplicate entry 'fjlsdkfj@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 05:52:39 --> mysqli_sql_exception: Duplicate entry 'fjlsdkfj@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-12-01 05:53:25 --> Unsupported operand types: string + string
in APPPATH\Controllers\Myhome.php on line 39.
 1 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
 2 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-01 05:53:37 --> mysqli_sql_exception: Duplicate entry 'dfdsf@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 05:55:43 --> mysqli_sql_exception: Duplicate entry 'prabhakar@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 06:00:43 --> mysqli_sql_exception: Duplicate entry 'jagan.mains@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 06:03:50 --> mysqli_sql_exception: Duplicate entry 'jagan.mains@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
ERROR - 2022-12-01 06:12:07 --> mysqli_sql_exception: Duplicate entry 'jagan.mains@gmail.com' for key 'email' in C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\vedatrix\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\xampp\htdocs\vedatrix\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\xampp\htdocs\vedatrix\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\xampp\htdocs\vedatrix\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\vedatrix\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\vedatrix\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\vedatrix\app\Controllers\Myhome.php(32): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(927): App\Controllers\Myhome->createContact()
#9 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Myhome))
#10 C:\xampp\htdocs\vedatrix\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\vedatrix\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\vedatrix\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#13 {main}
